# Generated by Django 5.2.8 on 2025-11-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('category', models.CharField(choices=[('interview_request', 'Interview Request'), ('interview_confirmation', 'Interview Confirmation'), ('interview_reschedule', 'Interview Reschedule'), ('interview_cancellation', 'Interview Cancellation'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('general', 'General')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('toEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('toPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('retryCount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('interview_request', 'Interview Request'), ('interview_confirmation', 'Interview Confirmation'), ('interview_reschedule', 'Interview Reschedule'), ('interview_cancellation', 'Interview Cancellation'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('general', 'General')], max_length=50)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For email notifications', max_length=255, null=True)),
                ('body', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
            },
        ),
    ]
