# Generated by Django 5.2.8 on 2025-11-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'userType': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='employer_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'userType': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='officeLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.officelocation'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['employer', 'status'], name='interviews_employe_404416_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['provider', 'status'], name='interviews_provide_87c57a_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['date', 'time'], name='interviews_date_83d76d_idx'),
        ),
    ]
