# Generated by Django 5.2.8 on 2025-11-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='isHired',
            field=models.BooleanField(default=False, help_text='Whether employer hired the provider after interview'),
        ),
    ]
