# Generated by Django 5.2.8 on 2025-11-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_ishired'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='improvements',
            field=models.TextField(blank=True, help_text='Areas for improvement', null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='strengths',
            field=models.TextField(blank=True, help_text='What the provider did well', null=True),
        ),
    ]
