# Generated by Django 5.2.8 on 2025-11-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('adminNotes', models.TextField(blank=True, help_text='Internal notes for admin use', null=True)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'userType': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(blank=True, limit_choices_to={'userType': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'db_table': 'verifications',
                'ordering': ['-submittedAt'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(choices=[('id', 'National ID'), ('license', "Driver's License"), ('profile_photo', 'Profile Photo'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('document', models.FileField(upload_to='verifications/')),
                ('fileName', models.CharField(max_length=255)),
                ('fileSize', models.IntegerField(help_text='File size in bytes')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verifications.verification')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'db_table': 'verification_documents',
                'ordering': ['-uploadedAt'],
            },
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['provider', 'status'], name='verificatio_provide_e87b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['status', 'submittedAt'], name='verificatio_status_940c6f_idx'),
        ),
    ]
