# Generated by Django 5.2.3 on 2025-11-28 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('motorbike-rider', 'Motorbike Rider'), ('car-driver', 'Car Driver'), ('truck-driver', 'Truck Driver')], max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Job requirements and qualifications')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities', null=True)),
                ('employmentType', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary')], default='full-time', max_length=20)),
                ('experienceRequired', models.IntegerField(help_text='Minimum years of experience required')),
                ('salaryMin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaryMax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaryCurrency', models.CharField(default='KES', max_length=10)),
                ('salaryPeriod', models.CharField(default='monthly', help_text='e.g., monthly, weekly, hourly', max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('specificLocation', models.TextField(blank=True, help_text='Specific work location details', null=True)),
                ('isRemote', models.BooleanField(default=False)),
                ('benefits', models.TextField(blank=True, help_text='Additional benefits offered', null=True)),
                ('numberOfPositions', models.IntegerField(default=1, help_text='Number of positions available')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('filled', 'Filled')], default='active', max_length=20)),
                ('applicationDeadline', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(limit_choices_to={'userType': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'db_table': 'jobs',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLetter', models.TextField(blank=True, help_text='Cover letter or message', null=True)),
                ('expectedSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availableFrom', models.DateField(blank=True, help_text='When can you start?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_requested', 'Interview Requested'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=30)),
                ('employerNotes', models.TextField(blank=True, help_text='Internal notes by employer', null=True)),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('provider', models.ForeignKey(limit_choices_to={'userType': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_applications',
                'ordering': ['-appliedAt'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer', 'status'], name='jobs_employe_e5cffa_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='jobs_categor_baa678_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'createdAt'], name='jobs_status_184ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['provider', 'status'], name='job_applica_provide_748374_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'appliedAt'], name='job_applica_status_db0e3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'provider')},
        ),
    ]
