# Generated by Django 5.2.8 on 2025-11-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('userType', models.CharField(choices=[('provider', 'Service Provider'), ('employer', 'Employer'), ('admin', 'Administrator')], max_length=20)),
                ('companyName', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('motorbike-rider', 'Motorbike Rider'), ('car-driver', 'Car Driver'), ('truck-driver', 'Truck Driver')], max_length=50, null=True)),
                ('experience', models.IntegerField(blank=True, help_text='Years of experience', null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('lastActive', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-dateJoined'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredName', models.CharField(help_text='Official registered name', max_length=255)),
                ('category', models.CharField(choices=[('motorbike-rider', 'Motorbike Rider'), ('car-driver', 'Car Driver'), ('truck-driver', 'Truck Driver')], max_length=50)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('bio', models.TextField(blank=True, null=True)),
                ('idNumber', models.CharField(max_length=50)),
                ('licenseNumber', models.CharField(max_length=50)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('idDocument', models.FileField(blank=True, null=True, upload_to='documents/ids/')),
                ('licenseDocument', models.FileField(blank=True, null=True, upload_to='documents/licenses/')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('availability', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('totalInterviews', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
                'db_table': 'provider_profiles',
            },
        ),
        migrations.CreateModel(
            name='SavedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savedAt', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_providers', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Provider',
                'verbose_name_plural': 'Saved Providers',
                'db_table': 'saved_providers',
                'ordering': ['-savedAt'],
                'unique_together': {('employer', 'provider')},
            },
        ),
    ]
