# Generated by Django 5.2.8 on 2025-11-20 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(help_text='Official company name', max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('contactPerson', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('companySize', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registrationNumber', models.CharField(max_length=100)),
                ('registrationCertificate', models.FileField(blank=True, null=True, upload_to='documents/certificates/')),
                ('officeAddress', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'db_table': 'employer_profiles',
            },
        ),
    ]
