# Generated by Django 5.2.8 on 2025-11-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='willingToRelocate',
            field=models.BooleanField(default=False, help_text='Willing to relocate for work'),
        ),
    ]
