# Generated by Django 5.2.8 on 2025-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_providerprofile_willingtorelocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='preferredLocations',
            field=models.TextField(blank=True, help_text='Comma-separated preferred working locations', null=True),
        ),
    ]
