# Generated by Django 5.2.8 on 2025-11-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingDays', models.JSONField(blank=True, default=list, help_text='List of working days')),
                ('workingHours', models.JSONField(blank=True, default=dict, help_text='Start and end times')),
                ('availableWeekends', models.BooleanField(default=False)),
                ('availableHolidays', models.BooleanField(default=False)),
                ('emailNotifications', models.BooleanField(default=True)),
                ('smsNotifications', models.BooleanField(default=False)),
                ('interviewAlerts', models.BooleanField(default=True)),
                ('marketingEmails', models.BooleanField(default=False)),
                ('preferredRegions', models.JSONField(blank=True, default=list, help_text='List of preferred work regions')),
                ('maxTravelDistance', models.IntegerField(default=50, help_text='Maximum travel distance in km')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
