# Generated by Django 5.2.3 on 2025-11-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employerType',
            field=models.CharField(blank=True, choices=[('company', 'Company/Organization'), ('individual', 'Individual/Household')], help_text='Type of employer: company or individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='companyName',
            field=models.CharField(blank=True, help_text='Official company name (for companies)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Company description or individual hiring needs', null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
